
name:  Check Pull Request to dev branch

on:

  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: {java-version: 1.17}

      - name: Build app
        run: |
         ./gradlew :app:build -PstorePassword=${STORE_PASSWORD} -PkeyAlias=${KEY_ALIAS} -PkeyPassword=${KEY_PASSWORD}

      - name: Check status
        run: echo "Check build status"

      - name: Set failed if build failed
        if: failure()
        run: |
          echo "::error::Build failed"