
name: Build and sent to QA prodQa

on:
  pull_request:
    #    types:
    #      - closed
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: { java-version: 1.17 }
      - name: Build and send application prodQa to App Distribution
        env:
          CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        run: |
          echo CREDENTIAL_FILE_CONTENT > ./app/serviceCredentialsFile.json
          echo "App type: prodQa" >> ./app/releaseNotes.txt
          echo "buildNumber=${GITHUB_RUN_NUMBER}" >> ./app/releaseNotes.txt
          ./gradlew appDistributionToQaProdQa

      - name: Check status
        run: echo "Check build status and send status"
      - name: Set failed if build failed
        if: failure()
        run: |
          echo "::error::Build or send build prodQa to App Distribution failed"
